Se appropriate sizes for images

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -110,7 +110,7 @@ function _buildDoc
         "Build")
             # Build the doc.
             cat ../src/templates/head.html > "$fileOut"
-            cat "$srcFile" | insertYoutube | pandoc -f markdown -t html >> "$fileOut"
+            cat "$srcFile" | insertYoutube | images "$myTag" | pandoc -f markdown -t html >> "$fileOut"
             sed -i "s#~!TITLE!~#$title#g;s#~!TITLEIMAGE!~#$titleImage#g;s#~!TAGS!~#$tags#g" "$fileOut"
             # TODO Create a wrapper for these.
             echo "<DIV CLASS=\"recommendedItems\">" >> "$fileOut"
@@ -378,6 +378,67 @@ function buildPreview
     value="$(grep -v '\(^<!-- \|^$\|^#\|^!\|^\[\|^----\|^====\|^\\\\\|^.$\|^http\)' "$inFile"| tr ' ' '\n' | head -n "$previewLength" | tr '\n' ' ')"
     
     echo "$value" > "$outFile"
+}
+
+function images
+{
+    local myTag="$1"
+    
+    while read -r line;do
+        if [ "${line::2}" == '![' ]; then
+            description="$(echo "$line" | sed 's/^..//g; s/\].*$//g')"
+            file="$(echo "$line" | sed 's/^.*(//g; s/).*$//g')"
+            
+            previewFile="$(getImageName "$file" "_preview")"
+            imageFile="$(getImageName "$file" "_viewable")"
+            
+            if [ -f "$myTag/$file" ]; then
+                imageMaxSize "$myTag/$file" "$myTag/$previewFile" "$previewMaxSize"
+                imageMaxSize "$myTag/$file" "$myTag/$imageFile" "$useableMaxSize"
+                
+                rm "$myTag/$file"
+            fi
+            
+            if [ -f "$myTag/$previewFile" ] && [ -f "$myTag/$imageFile" ] ; then
+                echo "<p><a href=\"$imageFile\" target=\"_blank\"><img alt=\"$description\" src=\"$previewFile\" /></a><br>Above: $description</p>"
+            else
+                echo "Could not find \"$myTag/$previewFile\" & \"$myTag/$imageFile\" in \"$(pwd)\". So this has been skipped in the final output." >&2
+            fi
+        else
+            echo "$line"
+        fi
+    done
+}
+
+function imageMaxSize
+{
+    local imageInFile="$1"
+    local imageOutFile="$2"
+    local imageMaxSize="$3"
+    
+    if [ -e "$imageOutFile" ]; then
+        true # Don't do anything if we already have it. This can be re-done by doing a ./bin/freshBuild
+    elif [ -e "$imageInFile" ]; then
+        read x y < <(identify -format "%w %h" "$imageInFile")
+        
+        if [ $x -gt $y ]; then
+            if [ "$x" -gt "$imageMaxSize" ]; then
+                let newY=$y*$imageMaxSize/$x
+                convert -resize "${imageMaxSize}x${newY}" "$imageInFile" "$imageOutFile"
+            else
+                cp "$imageInFile" "$imageOutFile"
+            fi
+        else
+            if [ "$y" -gt "$imageMaxSize" ]; then
+                let newX=$x*$imageMaxSize/$y
+                convert -resize "${newY}x${imageMaxSize}" "$imageInFile" "$imageOutFile"
+            else
+                cp "$imageInFile" "$imageOutFile"
+            fi
+        fi
+    else
+        echo "imageMaxSize: Could not find \"$imageInFile\"." >&2
+    fi
 }
 
 function insertYoutube
